### ISSUE TITLE
Can you add FusePLM

### ISSUE THREAD

**Issue by kvelmurugan78** [sampl/madeina2#51]
Please add www.fuseplm.com ?

Thanks,
Vel.

**Comment by sampl** [comment]
Hi Vel, could you tell us a little more about Fuse so I can make sure it fits [our guidelines](https://github.com/sampl/madeina2/blob/master/README.md)?

If it's a fit, you can add it yourself and submit a pull request to this repo.

**Comment by kvelmurugan78** [comment]
Hi, we just pitched in A2NewTech last Tuesday. Here are some details about FusePLM.
FusePLM is an affordable, easy-to-use and configure cloud-based SaaS system that helps design and manufacturing companies manage their Product’s Parts, Bill-of-Materials and change process.
Key benefits are:
•        Cards-based workflow reduces time to close change orders
•        Increases user efficiency by integrating workflows tasks into the user’s To-Do list
•        Minimize risk associated with product changes through an easy-to-understand Impact Visualizer
•        Industry-first AI-enabled PLMBot minimizes user-learning curve
